# =========================================================
# APPLICATION
# =========================================================

spring.application.name=ai-recruitment-system
server.port=8081


# =========================================================
# POSTGRESQL
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_recruitment_db
spring.datasource.username=postgres
spring.datasource.password=1901

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =========================================================
# CANDIDATE SELECTION
# 85% and above = selected
# Below 85% = rejected
# =========================================================

app.selection-threshold=85.0


# =========================================================
# EMAIL SENDER
# Actual Gmail values are entered in STS Environment
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# =========================================================
# DEVELOPMENT ERROR DETAILS
# =========================================================

server.error.include-message=always
server.error.include-binding-errors=always